/**
 * Python / forge_plan constraints for submit_plan_code.
 * Cheat sheet is autogenerated from forge_plan docstrings.
 *
 * Regenerate: `pnpm generate:forge-plan-cheat-sheet`
 */
import { FORGE_PLAN_API_CHEAT_SHEET } from "@/lib/plans/prompts/forge_plan_api_cheat_sheet.generated";

export { FORGE_PLAN_API_CHEAT_SHEET };

export function buildPythonCodegenRules(): string {
  return [
    "These rules apply to the Python in submit_plan_code only — not to your user-visible chat message (keep chat to one short sentence after success; see Assistant reply style in the system prompt).",
    "",
    "When calling submit_plan_code, provide the complete Python script body for run.py (not a snippet).",
    "The script must:",
    "- Read current_plan.json from the working directory",
    "- Write output/plan.json (valid workout plan JSON, schemaVersion 3.0.0)",
    "- Prefer the forge_plan API below over hand-built dicts",
    "- Avoid network access, subprocesses, and reading files other than current_plan.json",
    "- Be deterministic; use for-loops or data structures to build every week/day/exercise the user requested — do not stop after the first week or day",
    "",
    "Full-program rule:",
    "- If the user's message specifies weeks, days per week, or a full block/mesocycle, generate all of it in this one script.",
    "- Unroll or loop Plan.add_week / Week.add_day / Day.add_exercise / Exercise.add_sets until the requested structure is complete.",
    "- Only produce a partial plan (e.g. one day) when the user explicitly asks for a sample or partial draft.",
    "",
    "Cheat sheet (API signatures, schema rules, and examples):",
    FORGE_PLAN_API_CHEAT_SHEET,
  ].join("\n");
}
