/**
 * Python / forge_plan constraints for submit_plan_code.
 * Cheat sheet is autogenerated from forge_plan docstrings.
 *
 * Regenerate: `pnpm generate:forge-plan-cheat-sheet`
 */
import { FORGE_PLAN_API_CHEAT_SHEET } from "@/lib/ai/plan-chat/prompts/forge_plan_api_cheat_sheet.generated";

export { FORGE_PLAN_API_CHEAT_SHEET };

export function buildPythonCodegenRules(): string {
  return [
    "These rules apply to the Python in submit_plan_code only — not to your user-visible chat message (keep chat to one short sentence after success; see Assistant reply style in the system prompt).",
    "",
    "When calling submit_plan_code, provide the complete Python script body for run.py (not a snippet).",
    "The script must:",
    "- Read current_plan.json from the working directory",
    "- Write output/plan.json (valid workout plan JSON, schemaVersion 2.1.0)",
    "- Prefer the forge_plan API below over hand-built dicts",
    "- Avoid network access, subprocesses, and reading files other than current_plan.json",
    "- Be deterministic; use for-loops or data structures to build every week/day/exercise the user requested — do not stop after the first week or day",
    "",
    "Full-program rule:",
    "- If the user's message specifies weeks, days per week, or a full block/mesocycle, generate all of it in this one script.",
    "- Unroll or loop add_week / add_day / add_exercise / add_superset / add_set until the requested structure is complete.",
    "- Only produce a partial plan (e.g. one day) when the user explicitly asks for a sample or partial draft.",
    "",
    "Reps and notes (schema — invalid output fails validation):",
    "- add_set reps must be a plain integer count (e.g. 3, 5, 15). Do not embed per-side, time, or spreadsheet notation in reps.",
    '- Invalid reps examples: "3/side", "6/side", "2x30s", "30s", "5/5", "1 (3 jumps)".',
    '- Put coaching qualifiers in add_set(notes=...) — e.g. notes="per side", notes="30 sec", notes="2 sets".',
    "- Optional rep complexes only: reps=\"5+5+5\" when you need plus-separated counts; otherwise use int reps + notes.",
    "",
    "Critical validation pitfalls (also listed in the cheat sheet):",
    "- Do not pass day codes to add_day — forge_plan derives w1d1, w1d2, etc. from week/day order",
    "- Each week needs >=1 day; each day >=1 block; each exercise >=1 set",
    "- Supersets: plan.add_superset(week_index, day_index) then superset.add_exercise(name, rounds=N, reps=..., load_value=..., unit=...) for each exercise",
    "- add_set: use keyword args (week_index, day_index, reps, load_value, notes=...); omit exercise_index to target the last exercise",
    "",
    "Cheat sheet:",
    FORGE_PLAN_API_CHEAT_SHEET,
  ].join("\n");
}
