import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Python / forge_plan constraints for submit_plan_code.
 * Cheat sheet is autogenerated from forge_plan docstrings.
 *
 * Regenerate: `pnpm generate:forge-plan-cheat-sheet`
 */
function loadForgePlanApiCheatSheet(): string {
  const path = join(__dirname, "forge_plan_api_cheat_sheet.txt");
  return readFileSync(path, "utf8").trim();
}

export const FORGE_PLAN_API_CHEAT_SHEET = loadForgePlanApiCheatSheet();

export function buildPythonCodegenRules(): string {
  return [
    "When calling submit_plan_code, provide the complete Python script body for run.py (not a snippet).",
    "The script must:",
    "- Read current_plan.json from the working directory",
    "- Write output/plan.json (valid workout plan JSON, schemaVersion 2.0.0)",
    "- Prefer the forge_plan API below over hand-built dicts",
    "- Avoid network access, subprocesses, and reading files other than current_plan.json",
    "- Stay short and deterministic",
    "",
    "Cheat sheet:",
    FORGE_PLAN_API_CHEAT_SHEET,
  ].join("\n");
}
