allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - "@ai-sdk/*"
  - "@rolldown/*"
  - "@vercel/*"
  - "@workflow/*"
  - ai
  - experimental-ai-sdk-code-mode
  - eve
  - nitro
  - rolldown
  - workflow
