insert into exercises (name, normalized_name)
values
  ('Back Squat', 'back squat'),
  ('Front Squat', 'front squat'),
  ('Box Squat', 'box squat'),
  ('Goblet Squat', 'goblet squat'),
  ('Bench Press', 'bench press'),
  ('Close Grip Bench Press', 'close grip bench press'),
  ('Incline Bench Press', 'incline bench press'),
  ('Dumbbell Bench Press', 'dumbbell bench press'),
  ('Deadlift', 'deadlift'),
  ('Conventional Deadlift', 'conventional deadlift'),
  ('Sumo Deadlift', 'sumo deadlift'),
  ('Romanian Deadlift', 'romanian deadlift'),
  ('Stiff Leg Deadlift', 'stiff leg deadlift'),
  ('Overhead Press', 'overhead press'),
  ('Push Press', 'push press'),
  ('Barbell Row', 'barbell row'),
  ('Dumbbell Row', 'dumbbell row'),
  ('Power Clean', 'power clean'),
  ('Hang Clean', 'hang clean'),
  ('Snatch', 'snatch'),
  ('Hang Snatch', 'hang snatch'),
  ('Clean and Jerk', 'clean and jerk'),
  ('Pull Up', 'pull up'),
  ('Chin Up', 'chin up'),
  ('Lat Pulldown', 'lat pulldown'),
  ('Push Up', 'push up'),
  ('Dip', 'dip'),
  ('Barbell Lunge', 'barbell lunge'),
  ('Walking Lunge', 'walking lunge'),
  ('Bulgarian Split Squat', 'bulgarian split squat'),
  ('Step Up', 'step up'),
  ('Hip Thrust', 'hip thrust'),
  ('Glute Bridge', 'glute bridge'),
  ('Good Morning', 'good morning'),
  ('Kettlebell Swing', 'kettlebell swing'),
  ('Farmer Carry', 'farmer carry'),
  ('Front Rack Carry', 'front rack carry'),
  ('Biceps Curl', 'biceps curl'),
  ('Triceps Extension', 'triceps extension'),
  ('Calf Raise', 'calf raise')
on conflict do nothing;
